---
title: "Simulation_Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
mms_rsd <- function(ress){
  res = ress [-1]
  mms <- cbind(median(sapply(c(1:200),function(i) max(res[1:5,i]))),
               median(sapply(c(1:200),function(i) max(res[16:20,i]))),
               median(sapply(c(1:200),function(i) max(res[21:25,i]))),
               median(sapply(c(1:200),function(i) max(res[26:30,i]))),
               median(sapply(c(1:200),function(i) max(res[31:35,i]))),
               median(sapply(c(1:200),function(i) max(res[36:40,i]))),
               median(sapply(c(1:200),function(i) max(res[41:45,i]))),
               median(sapply(c(1:200),function(i) max(res[46:50,i]))),
               median(sapply(c(1:200),function(i) max(res[51:55,i]))),
               median(sapply(c(1:200),function(i) max(res[56:60,i]))))
  s1 = (as.numeric(quantile(sapply(c(1:200),function(i) max(res[1:5,i])),0.75))-as.numeric(quantile(sapply(c(1:200),function(i) max(res[1:5,i])),0.25)))/1.349
  s4 = (as.numeric(quantile(sapply(c(1:200),function(i) max(res[16:20,i])),0.75))-as.numeric(quantile(sapply(c(1:200),function(i) max(res[1:5,i])),0.25)))/1.349
  s5 = (as.numeric(quantile(sapply(c(1:200),function(i) max(res[21:25,i])),0.75))-as.numeric(quantile(sapply(c(1:200),function(i) max(res[1:5,i])),0.25)))/1.349
  s6 = (as.numeric(quantile(sapply(c(1:200),function(i) max(res[26:30,i])),0.75))-as.numeric(quantile(sapply(c(1:200),function(i) max(res[1:5,i])),0.25)))/1.349
  s7 = (as.numeric(quantile(sapply(c(1:200),function(i) max(res[31:35,i])),0.75))-as.numeric(quantile(sapply(c(1:200),function(i) max(res[31:35,i])),0.25)))/1.349
  s8 = (as.numeric(quantile(sapply(c(1:200),function(i) max(res[36:40,i])),0.75))-as.numeric(quantile(sapply(c(1:200),function(i) max(res[36:40,i])),0.25)))/1.349
  s9 = (as.numeric(quantile(sapply(c(1:200),function(i) max(res[41:45,i])),0.75))-as.numeric(quantile(sapply(c(1:200),function(i) max(res[41:45,i])),0.25)))/1.349
  s10 = (as.numeric(quantile(sapply(c(1:200),function(i) max(res[46:50,i])),0.75))-as.numeric(quantile(sapply(c(1:200),function(i) max(res[46:50,i])),0.25)))/1.349
  s11 = (as.numeric(quantile(sapply(c(1:200),function(i) max(res[51:55,i])),0.75))-as.numeric(quantile(sapply(c(1:200),function(i) max(res[51:55,i])),0.25)))/1.349
  s12 = (as.numeric(quantile(sapply(c(1:200),function(i) max(res[56:60,i])),0.75))-as.numeric(quantile(sapply(c(1:200),function(i) max(res[56:60,i])),0.25)))/1.349
  rsd <- cbind(s1,s4,s5,s6,s7,s8,s9,s10,s11,s12)
  tmpp <- (as.data.frame(rbind(mms,rsd)))
  names(tmpp) <- c("ADD","KF-50","DC-50","MV-50","KF-33","DC-33","MV-33","KF-67","DC-67","MV-67")
  row.names(tmpp) = c("MMS","RSD")
  return (tmpp)
}

time_get<- function(ress){
  res = ress [-1]
  time_ <- cbind(mean(sapply(c(1:200),function(i) res[61,i])),
               mean(sapply(c(1:200),function(i) res[64,i])),
               mean(sapply(c(1:200),function(i) res[65,i])),
               mean(sapply(c(1:200),function(i) res[66,i])),
               mean(sapply(c(1:200),function(i) res[67,i])),
               mean(sapply(c(1:200),function(i) res[68,i])),
               mean(sapply(c(1:200),function(i) res[69,i])),
               mean(sapply(c(1:200),function(i) res[70,i])),
               mean(sapply(c(1:200),function(i) res[71,i])),
               mean(sapply(c(1:200),function(i) res[72,i])))
  time_sd <- cbind(sd(sapply(c(1:200),function(i) res[61,i])),
                   sd(sapply(c(1:200),function(i) res[64,i])),
                   sd(sapply(c(1:200),function(i) res[65,i])),
                   sd(sapply(c(1:200),function(i) res[66,i])),
                   sd(sapply(c(1:200),function(i) res[67,i])),
                   sd(sapply(c(1:200),function(i) res[68,i])),
                   sd(sapply(c(1:200),function(i) res[69,i])),
                   sd(sapply(c(1:200),function(i) res[70,i])),
                   sd(sapply(c(1:200),function(i) res[71,i])),
                   sd(sapply(c(1:200),function(i) res[72,i])))
  tmpp <- (as.data.frame(rbind(time_,time_sd)))
  names(tmpp) <- c("ADD","KF-50","DC-50","MV-50",
                   "KF-33","DC-33","MV-33","KF-67","DC-67","MV-67")
  row.names(tmpp) = c("Average Time","Standard Deviation")
  return (tmpp)
}


file_root = root_path = paste(dirname(getwd()),"/Intermediate/",sep="")

```

# Linear Model Simulation Case
```{r}
lm_res1 <- read.csv(paste(file_root,"LM/Full_res1_time.csv",sep=""))
lm_res2 <- read.csv(paste(file_root,"LM/Full_res2_time.csv",sep=""))
lm_res4 <- read.csv(paste(file_root,"LM/Full_res4_time.csv",sep=""))
lm_res5 <- read.csv(paste(file_root,"LM/Full_res5_time.csv",sep=""))
lm_res7 <- read.csv(paste(file_root,"LM/Full_res7_time.csv",sep=""))
lm_res8 <- read.csv(paste(file_root,"LM/Full_res8_time.csv",sep=""))
lm_res10 <- read.csv(paste(file_root,"LM/Full_res10_time.csv",sep=""))
lm_res11 <- read.csv(paste(file_root,"LM/Full_res11_time.csv",sep=""))
```

```{r}
t(mms_rsd(lm_res4))
```

```{r}
t(mms_rsd(lm_res10))
```


```{r}
t(mms_rsd(lm_res1))
```
```{r}
t(mms_rsd(lm_res7))
```
```{r}
t(time_get(cbind(lm_res4,lm_res10,lm_res1,lm_res7)))
```
```{r}
t(mms_rsd(lm_res5))
```
```{r}
t(mms_rsd(lm_res11))
```
```{r}
t(mms_rsd(lm_res2))
```
```{r}
t(mms_rsd(lm_res8))
```
```{r}
t(time_get(cbind(lm_res5,lm_res11,lm_res2,lm_res8)))

```



# Generalized Linear Model Case
```{r}
glm_res1 <- read.csv(paste(file_root,"GLM/Full_res1_time.csv",sep=""))
glm_res2 <- read.csv(paste(file_root,"GLM/Full_res2_time.csv",sep=""))
glm_res4 <- read.csv(paste(file_root,"GLM/Full_res4_time.csv",sep=""))
glm_res5 <- read.csv(paste(file_root,"GLM/Full_res5_time.csv",sep=""))
glm_res7 <- read.csv(paste(file_root,"GLM/Full_res7_time.csv",sep=""))
glm_res8 <- read.csv(paste(file_root,"GLM/Full_res8_time.csv",sep=""))
glm_res10 <- read.csv(paste(file_root,"GLM/Full_res10_time.csv",sep=""))
glm_res11 <- read.csv(paste(file_root,"GLM/Full_res11_time.csv",sep=""))
```

```{r}
t(mms_rsd(glm_res4))
```

```{r}
t(mms_rsd(glm_res10))
```


```{r}
t(mms_rsd(glm_res1))
```
```{r}
t(mms_rsd(glm_res7))
```
```{r}
t(time_get(cbind(glm_res4,glm_res10,glm_res1,glm_res7)))
```
```{r}
t(mms_rsd(glm_res5))
```
```{r}
t(mms_rsd(glm_res11))
```
```{r}
t(mms_rsd(glm_res2))
```
```{r}
t(mms_rsd(glm_res8))
```
```{r}
t(time_get(cbind(glm_res5,glm_res11,glm_res2,glm_res8)))

```



# Cox Model
```{r}
cox_res1 <- read.csv(paste(file_root,"COX/Full_res1_time.csv",sep=""))
cox_res2 <- read.csv(paste(file_root,"COX/Full_res2_time.csv",sep=""))
cox_res4 <- read.csv(paste(file_root,"COX/Full_res4_time.csv",sep=""))
cox_res5 <- read.csv(paste(file_root,"COX/Full_res5_time.csv",sep=""))
cox_res7 <- read.csv(paste(file_root,"COX/Full_res7_time.csv",sep=""))
cox_res8 <- read.csv(paste(file_root,"COX/Full_res8_time.csv",sep=""))
cox_res10 <- read.csv(paste(file_root,"COX/Full_res10_time.csv",sep=""))
cox_res11 <- read.csv(paste(file_root,"COX/Full_res11_time.csv",sep=""))
```




```{r}
t(mms_rsd(cox_res4))
```
```{r}
t(mms_rsd(cox_res10))
```
```{r}
t(mms_rsd(cox_res1))
```

```{r}
t(mms_rsd(cox_res7))
```
```{r}
t(time_get(cbind(cox_res4,cox_res10,cox_res1,cox_res7)))
```
```{r}
t(mms_rsd(cox_res5))
```
```{r}
t(mms_rsd(cox_res11))
```
```{r}
t(mms_rsd(cox_res2))
```
```{r}
t(mms_rsd(cox_res8))
```
```{r}
time_get(cbind(cox_res5,cox_res11,cox_res2,cox_res8))
```
