---
title: "CaseStudy-WebDeveloper"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning=FALSE)
```
```{r}
library(readr)
library(Icens)
library(interval)
library(MASS)
library(dplyr)
library(energy)

```

# Loading Data 


```{r}

dt <- read_csv("../Data/Web.csv")
REAL_TEST = dt
l = REAL_TEST$l
r =REAL_TEST$r
s = as.data.frame(subset(REAL_TEST, select = -c(l,r,Description) ))

words = read.csv("../Data/UtilizedWords.csv")
```





# ADD-SIS
```{r}
intervals <- initcomputeMLE(l,r)
max_tmp <- max(intervals$intmap[2,])
min_tmp <- min(intervals$intmap[1,])
if (is.finite(max_tmp)) {end <- max_tmp} 
if (is.infinite(max_tmp)) {end <-max(intervals$intmap[1,])+100 }
if (is.finite(min_tmp)) {start <- min_tmp} 
if (is.infinite(min_tmp)) {start <-min(intervals$intmap[2,])-100 }
X1<-c(as.integer(start/100):as.integer(end/100))
X2<-X1+1
basis<- data.frame(x1=100*X1,x2=100*X2)

int_split <- function(i,df){
  start <- as.numeric(df[i,][1])/100
  end <- as.numeric(df[i,][2])/100
  difs <- end-start-1
  x1 <- 100*(start+c(0:difs))
  x2 <- 100*(start+1+c(0:difs))
  x3 <- as.numeric(rep(df[i,][3]/(as.numeric(difs+1)),difs+1))
  return (data.frame(x1=x1,x2=x2,x3=x3))
  
}




screen_add <- function(no,s) {
  #word1 <- sapply(c(1:length(sub)[1]),function(i) grepl(dict[no],kk[i]))
  x1 <- as.vector(unlist(s[as.character(no)]))
  every = data.frame(l=l,r=r,x=x1)
  part1 = every[every$x==1,c('l','r')]
  part2 = every[every$x==0,c('l','r')]
  a <- initcomputeMLE(part1$l,part1$r)
  b <- initcomputeMLE(part2$l,part2$r)
  df1 <- data.frame(cbind(t(a$intmap),a$pf))
  df2 <- data.frame(cbind(t(b$intmap),b$pf))
  if (length(a$pf)==1){
    if (max(df2$X2)>1) {kk2 = lapply(c(1:dim(df2)[1]),int_split,df=df2)
    pp2 = bind_rows(kk2)}
    if (max(df2$X2)==1) {ind_start <- (df2$X1/100)[1]
    ind_end<- (df2$X1/100)[2]
    pp2 <- data.frame(x1=100*c(ind_start:(ind_end-1)),
                      x2=100*c((ind_start+1):(ind_end)),
                      x3=rep(1/(end-start),as.numeric(ind_end-ind_start)))
    }
    tmp = merge(pp2,basis,all.y = TRUE)
    tmp[is.na(tmp$x3),c('x3')]<-0
    score_ = sum(100 * (cumsum(tmp$x3)))
  }
  else {
    kk1 = lapply(c(1:dim(df1)[1]),int_split,df=df1)
    pp1 = bind_rows(kk1)
    
    if (max(df2$X2)>1) {kk2 = lapply(c(1:dim(df2)[1]),int_split,df=df2)
    pp2 = bind_rows(kk2)}
    if (max(df2$X2)==1) {ind_start <- (df2$X1/100)[1]
    ind_end<- (df2$X1/100)[2]
    pp2 <- data.frame(x1=100*c(ind_start:(ind_end-1)),
                      x2=100*c((ind_start+1):(ind_end)),
                      x3=rep(1/(end-start),as.numeric(ind_end-ind_start)))
    }
    a1 = merge(pp1,basis,all.y = TRUE)
    a2 = merge(pp2,basis,all.y = TRUE)
    tmp <- merge(a1,a2,by='x1')
    tmp[is.na(tmp$x3.x),c('x3.x')]<-0
    tmp[is.na(tmp$x3.y),c('x3.y')]<-0
    score_ = sum(100 * abs(cumsum(tmp$x3.x)-cumsum(tmp$x3.y)))}
  
  return(score_)
  
  
}

```


# Screening
```{r}
score <- sapply(c(1:as.numeric(dim(s)[2])),screen_add,s=s)
res1 <- data.frame(screen=score)




mid <- 0.5*(l+r)
six <- 1/3*l + 2/3*r
third <- 2/3*l + 1/3*r

screen_ks<- function(i,y,s)
{
every = data.frame(cbind(y,as.vector(unlist(s[as.character(i)]))))
part1 = every[every$V2==0,c('y')]
part2 = every[every$V2==1,c('y')]
return (as.numeric(ks.test(part1,part2)$statistic))
}




screen_dc <- function(i,y,s)
{
  return (dcor(y,as.vector(unlist(s[as.character(i)]))))}
Fk<-function(X0,x) {
  Fk=c()
  for (i in 1:length(x))
  { Fk[i]=sum(X0<=x[i])/length(X0) }
  return(Fk)
}

Fkr<-function(X0,Y,yr,x) {
  Fkr=c()
  ind_yr=(Y==yr)
  for (i in 1:length(x))
  { Fkr[i]=sum((X0<=x[i])*ind_yr)/sum(ind_yr) }
  return(Fkr)
}

MV<-function(Xk,Y) {
  Fk0 <- Fk(Xk,Xk)
  Yr <- unique(Y)
  MVr <- c()
  for (r in 1:length(Yr)) {
    MVr[r] <- (sum(Y==Yr[r])/length(Y))*mean((Fkr(Xk,Y,Yr[r],Xk)-Fk0)^2)
  }
  MV <- sum(MVr)
  return(MV)
}



screen_mv <- function(i,s,y)
{return (abs(MV(Y=as.vector(unlist(s[as.character(i)])),Xk=y)))}


score2 = sapply(c(1:as.numeric(dim(s)[2])),screen_ks,y=third,s=s)
res2 <- data.frame(screen=score2)

score3 = sapply(c(1:as.numeric(dim(s)[2])),screen_dc,y=third,s=s)
res3 <- data.frame(screen=score3)


score4 = sapply(c(1:as.numeric(dim(s)[2])),screen_mv,y=third,s=s)
res4 <- data.frame(screen=score4)

score5 = sapply(c(1:as.numeric(dim(s)[2])),screen_ks,y=mid,s=s)
res5 <- data.frame(screen=score5)

score6 = sapply(c(1:as.numeric(dim(s)[2])),screen_dc,y=mid,s=s)
res6 <- data.frame(screen=score6)


score7 = sapply(c(1:as.numeric(dim(s)[2])),screen_mv,y=mid,s=s)
res7 <- data.frame(screen=score7)

score8 = sapply(c(1:as.numeric(dim(s)[2])),screen_ks,y=six,s=s)
res8 <- data.frame(screen=score8)



score9 = sapply(c(1:as.numeric(dim(s)[2])),screen_dc,y=six,s=s)
res9 <- data.frame(screen=score9)

score10 = sapply(c(1:as.numeric(dim(s)[2])),screen_mv,y=six,s=s)
res10 <- data.frame(screen=score10)


res_all <- as.data.frame(cbind(res1,res2,res3,res4,res5,res6,res7,res8,res9,res10))
```
# Selected Skills (Table S.4)
```{r} 
as.character((words$word[(length(res1$screen)+1 - rank(res1$screen))<21]))
```

# Model Fitting (Table S.5)
```{r}

fitting_prepare <- function(res,sub){
  totno <- dim(s)[2]
  ks <- data.frame(rank=totno-rank(res$screen),index=c(1:dim(s)[2]))
  x <- as.matrix(s[,ks[ks$rank<sub+1,]$index])
  data <- data.frame(l=l,r=r,sapply(c(1:dim(x)[2]),function(i) x[,i]))
  return (data)
  
}




model_fitting <- function(data,dis) {
  dt_tmp <- data[3:ncol(data)]
  if (dis == "weibull"){
    dt_tmp$l = data$l
    dt_tmp$r = data$r
    total <- dim(data)[2] - 2
    xkk = paste("X", 1:total, sep = "",collapse="+")
    model <- survreg(as.formula(paste("Surv(l,r,type='interval2')",
                                      xkk,sep="~")),data=dt_tmp,dist=dis)
    scsc <- model$loglik
    ress <- c(scsc[2],2*(scsc[2]-scsc[1]))
  }
  else {
    dt_tmp$l = log(data$l)
    dt_tmp$r = log(data$r)
    total <- dim(data)[2] - 3
    xkk = paste("X", 1:total, sep = "",collapse="+")
    model <- survreg(as.formula(paste("Surv(l,r,type='interval2')",
                                      xkk,sep="~")),data=dt_tmp,dist=dis)
    scsc <- model$loglik
    ress <- c(scsc[2],2*(scsc[2]-scsc[1]))}
  return (ress)
}

model_fittingtmp <- function(data,dis) {
  dt_tmp <- data[3:ncol(data)]
  if (dis == "weibull"){
    dt_tmp$l = data$l
    dt_tmp$r = data$r
    total <- dim(data)[2] - 2
    xkk = paste("X", 1:total, sep = "",collapse="+")
    modell <- survreg(as.formula(paste("Surv(l,r,type='interval2')",
                                      xkk,sep="~")),data=dt_tmp,dist=dis)
    #scsc <- model$loglik
    #ress <- c(scsc[2],2*(scsc[2]-scsc[1]))
  }
  else {
    dt_tmp$l = log(data$l)
    dt_tmp$r = log(data$r)
    total <- dim(data)[2] - 3
    xkk = paste("X", 1:total, sep = "",collapse="+")
    modell <- survreg(as.formula(paste("Surv(l,r,type='interval2')",
                                      xkk,sep="~")),data=dt_tmp,dist=dis)}
    #scsc <- model$loglik
    #ress <- c(scsc[2],2*(scsc[2]-scsc[1]))}}
  return (modell)
}

```
## Gaussian
```{r}

print ("gaussian")
number_variables =20
resGauss = as.data.frame(rbind(
      model_fitting(fitting_prepare(res1,number_variables),"gaussian"),
      model_fitting(fitting_prepare(res2,number_variables),"gaussian"),
      model_fitting(fitting_prepare(res3,number_variables),"gaussian"),
      model_fitting(fitting_prepare(res4,number_variables),"gaussian"),
      model_fitting(fitting_prepare(res5,number_variables),"gaussian"),
      model_fitting(fitting_prepare(res6,number_variables),"gaussian"),
      model_fitting(fitting_prepare(res7,number_variables),"gaussian"),
      model_fitting(fitting_prepare(res8,number_variables),"gaussian"),
      model_fitting(fitting_prepare(res9,number_variables),"gaussian"),
      model_fitting(fitting_prepare(res10,number_variables),"gaussian")))
row.names(resGauss) = c("ADD-SIS","KF-M1","DCSIS-M1","MVSIS-M1",
            "KF-M2","DCSIS-M2","MVSIS-M2",
            "KF-M3","DCSIS-M3","MVSIS-M3")
print (resGauss)

```
## Weibull
```{r}

resWeibull = as.data.frame(rbind(
  model_fitting(fitting_prepare(res1,number_variables),"weibull"),
  model_fitting(fitting_prepare(res2,number_variables),"weibull"),
  model_fitting(fitting_prepare(res3,number_variables),"weibull"),
  model_fitting(fitting_prepare(res4,number_variables),"weibull"),
  model_fitting(fitting_prepare(res5,number_variables),"weibull"),
  model_fitting(fitting_prepare(res6,number_variables),"weibull"),
  model_fitting(fitting_prepare(res7,number_variables),"weibull"),
  model_fitting(fitting_prepare(res8,number_variables),"weibull"),
  model_fitting(fitting_prepare(res9,number_variables),"weibull"),
  model_fitting(fitting_prepare(res10,number_variables),"weibull")))
row.names(resWeibull) = c("ADD-SIS","KF-M1","DCSIS-M1","MVSIS-M1",
            "KF-M2","DCSIS-M2","MVSIS-M2",
            "KF-M3","DCSIS-M3","MVSIS-M3")
print (resWeibull)
```
## Logistic
```{r}
resLogistic = as.data.frame(rbind(
  model_fitting(fitting_prepare(res1,number_variables),"logistic"),
  model_fitting(fitting_prepare(res2,number_variables),"logistic"),
  model_fitting(fitting_prepare(res3,number_variables),"logistic"),
  model_fitting(fitting_prepare(res4,number_variables),"logistic"),
  model_fitting(fitting_prepare(res5,number_variables),"logistic"),
  model_fitting(fitting_prepare(res6,number_variables),"logistic"),
  model_fitting(fitting_prepare(res7,number_variables),"logistic"),
  model_fitting(fitting_prepare(res8,number_variables),"logistic"),
  model_fitting(fitting_prepare(res9,number_variables),"logistic"),
  model_fitting(fitting_prepare(res10,number_variables),"logistic")))
row.names(resLogistic) = c("ADD-SIS","KF-M1","DCSIS-M1","MVSIS-M1",
            "KF-M2","DCSIS-M2","MVSIS-M2",
            "KF-M3","DCSIS-M3","MVSIS-M3")
print (resLogistic)
```